version: '3'
services:
  nats-client:
    image: minghsu0107/rtlsdr-example-nats-client
    restart: always
    command:
      - "99700000"
    environment:
      RTLSDR_RPC_SERV_ADDR: host.docker.internal
      RTLSDR_RPC_SERV_PORT: "40000"
      NATS_URL: nats://mytoken@nats:4222
      NATS_SUBJECT: "fm.raw"
    depends_on:
      - nats-box
  nats:
    image: nats:2.9.22
    ports:
      - "4222:4222"
    restart: always
    command:
      - -auth
      - mytoken
      - -js
  nats-box:
    image: natsio/nats-box:0.14.0
    depends_on:
      - nats
    command: >
      /bin/sh -c "
      nats -s nats://mytoken@nats:4222 str add "fm" --subjects="fm.*" --ack --max-msgs=-1 --max-msgs-per-subject=-1 --max-bytes=-1 --max-age=1y --storage=file --retention=limits --max-msg-size=1048576 --discard=old --replicas=1 --dupe-window="0s" --no-allow-rollup --no-deny-delete --no-deny-purge;
      nats -s nats://mytoken@nats:4222 str info "fm" -j; # output to json
      exit 0;
      "
